# Generated by Django 3.2.9 on 2021-11-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211114_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministries',
            options={'verbose_name': 'Ministry', 'verbose_name_plural': 'Ministries'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='userministry',
            options={'verbose_name': 'UserMinistry', 'verbose_name_plural': 'UserMinistries'},
        ),
        migrations.RemoveField(
            model_name='roles',
            name='ministry',
        ),
    ]
