# Generated by Django 3.2.9 on 2021-11-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211114_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministries',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='core.Roles'),
        ),
    ]
