# Generated by Django 3.2.9 on 2021-11-14 18:02

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userdetails_zones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'UserDetail', 'verbose_name_plural': 'UserDetails'},
        ),
        migrations.AlterModelOptions(
            name='zones',
            options={'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AddField(
            model_name='userdetails',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
