# Generated by Django 3.2.9 on 2021-11-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211114_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministries',
            name='roles',
            field=models.ManyToManyField(blank=True, to='core.Roles'),
        ),
    ]
