# Generated by Django 3.2.9 on 2021-11-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ministries_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
